### ISSUE TITLE
/usr/bin/ld: cannot find -lcsm-static

### ISSUE THREAD

**Issue by Durant35** [Durant35/smartcar_catkin_raspberrypi#5]
some strange error due to csm last installed

**Comment by Durant35** [comment]
```sh
git clone https://github.com/AndreaCensi/csm.git
```

**Comment by Durant35** [comment]
### Have modified setup.sh
```
```

**Comment by RH-Song** [comment]
> You can remove csm and git clone again
> git clone https://github.com/AndreaCensi/csm.git

It works.

**Comment by Durant35** [comment]
### has been fixed in current version
+ some explanation here： https://github.com/Durant35/smartcar_catkin_pc/issues/3
